batch_size: 128
# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: data_gen/ntu/NTU60_CV.npz
  split: train
  shear_amplitude: -1
  temperal_padding_ratio: -1
  p_interval: [0.95]
  window_size: 64
  stream: joint

test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: data_gen/ntu/NTU60_CV.npz
  split: test
  shear_amplitude: -1
  temperal_padding_ratio: -1
  window_size: 64
  p_interval: [0.95]
  stream: joint

# model
model: net.st_gcn.Model
model_args:
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 64
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d' 
    strategy: 'spatial'
  edge_importance_weighting: True

## optim
#nesterov: False
#weight_decay: 0.0
#base_lr: 3.
#optimizer: SGD
#step: [80]
#
## training
#device: [0]
#batch_size: 128
#test_batch_size: 128
#num_epoch: 100
#view: 'all'
#
## log
#save_interval: -1
#eval_interval: 5
