batch_size: 256
# feeder
train_feeder: feeder.ntu_feeder.Feeder_dual
train_feeder_args:
  data_path: data_gen/ntu/NTU60_CS.npz
  temperal_padding_ratio: 5
  shear_amplitude: 1
  l_ratio: [0.1, 1]
  window_size: 64
  p_interval: [0.1,1]
  split: 'train'
  stream: 'joint'

# model
model: net.st_gcn.Model
model_args:
#  feature_dim: 128
  in_channels: 3
  hidden_channels: 64 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

moving_average_decay: 0.99
projection_size: 1024
projection_hidden_size: 512




## optim
#nesterov: False
#weight_decay: 1e-4
#base_lr: 0.1
#optimizer: SGD
#step: [250]
#
## training
#device: [0]
#batch_size: 128
#test_batch_size: 128
#num_epoch: 300
#start_epoch: 0
#
## cross training
#topk: 1
#view: 'all'
#cross_epoch: 150
#context: True
#
## log
#save_interval: 5
#eval_interval: -1
