# feeder
train_feeder: feeder.ntu_feeder.Feeder_dual
train_feeder_args:
  data_path: data_gen/ntu/NTU60_CS.npz
  temperal_padding_ratio: 5
  shear_amplitude: 1
  l_ratio: [0.1, 1]
  window_size: 64
  p_interval: [0.1,1]
  split: 'train'
  stream: 'joint'

# model
model: net.gcn.Model
model_args:
#  feature_dim: 128
  in_channels: 3
  hidden_channels: 64 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# byol
moving_average_decay: 0.99
projection_size: 256
projection_hidden_size: 512
K: 512
tt: 0.03
ot: 0.1
drop_percent: 0.2

# training
batch_size: 500
epochs: 800
workers: 8
print_freq: 200
l: 0.1

## optim
learning_rate: 2
weight_decay: 1e-6